ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ALTER COLUMN mark INT CHECK (mark BETWEEN 1 AND 10), ALTER COLUMN student_id BIGINT NOT NULL, ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ALTER COLUMN grade INT CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype ALTER COLUMN name VARCHAR(255) UNIQUE;
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL, ALTER COLUMN amount DECIMAL NOT NULL, ALTER COLUMN payment_date DATETIME NOT NULL;

