ALTER TABLE Student MODIFY birthday DATE NOT NULL;
ALTER TABLE Mark MODIFY mark INT CHECK (mark BETWEEN 1 AND 10), student_id BIGINT NOT NULL, subject_id BIGINT NOT NULL;
ALTER TABLE Subject MODIFY grade INT CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE PaymentType MODIFY name VARCHAR(255) UNIQUE;
ALTER TABLE Payment MODIFY type_id BIGINT NOT NULL, amount DECIMAL NOT NULL, payment_date DATETIME NOT NULL;

